# Generated by Django 3.0.5 on 2020-05-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200515_0758'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table=None,
        ),
    ]
