# Generated by Django 3.0.5 on 2020-05-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200515_0810'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
    ]
