# Generated by Django 3.0.5 on 2020-05-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200515_0820'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account_account',
        ),
    ]
